input {
  http {
    port => 5000
    codec => json_lines
  }
}

filter {
  date {
    match => [ "datetime", "ISO8601" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dora"
  }

  stdout {
    codec => rubydebug
  }
}